### PR TITLE
Make attributes of Request Api configurable

### PR DESCRIPTION
**Pull request by tlueder**
Fixes https://github.com/sascha-egerer/phpstan-typo3/issues/50

I'm not entirely sure if I did that right... 

Please let me know your thoughts.

### CODE REVIEW

**Comment by sabbelasichon** [comment]
@tlueder Could you run vendor/bin/phpcbf locally to fix the CS errors.

**Comment by sabbelasichon** [comment]
@tlueder And many thanks for the PR. Very good catch.

**Comment by tlueder** [comment]
@sabbelasichon sure mate :)

**Comment by sascha-egerer** [comment]
Thanks you for taking care! This was already on my todo list!

**Comment by sascha-egerer** [comment]
Ok we have to fix some other issues with latest TYPO3 version before merging this one.

**Comment by tlueder** [comment]
OK, let me know if I can be of any help. I also see potential in adding the same for \TYPO3\CMS\Core\Site\Entity\Site::getAttribute()

If this is of interest.

**Comment by sascha-egerer** [comment]
> OK, let me know if I can be of any help.

I'll try to take care later today to get the tests running again and fix the current issues with latest TYPO3 version.


> I also see potential in adding the same for \TYPO3\CMS\Core\Site\Entity\Site::getAttribute()
> 
> If this is of interest.

Sure! Go for it! Thank you!

**Comment by tlueder** [comment]
I changed the class to \Psr\Http\Message\ServerRequestInterface to get the return types for both:

TYPO3\CMS\Core\Http\ServerRequest::getAttribute()

and 

TYPO3\CMS\Extbase\Mvc\Request::getAttribute()

Both classes implement ServerRequestInterface.

**Comment by sascha-egerer** [comment]
@tlueder Could you please rebase this one?

**Comment by tlueder** [comment]
Sure thing.

**Comment by sascha-egerer** [comment]
@tlueder I've just added some documentation, could you please check if that is fine?

**Comment by tlueder** [comment]
@sascha-egerer Thanks for that. I totally forgot about that.

**Pull request merged**
