### PR TITLE
Fixed class paths in context getAspect mapping

### PR DESCRIPTION
**Pull request by tlueder**
fixes https://github.com/sascha-egerer/phpstan-typo3/issues/54

### CODE REVIEW

**Comment by sascha-egerer** [comment]
We have to rebase this one after #56 ,  #57 and  #58 have been merged

**Comment by tlueder** [comment]
OK, I'll do that.

**Comment by tlueder** [comment]
I've rebased this PR and added

phpcs:ignore Squiz.Classes.ClassFileName.NoMatch

to match the naming of the other test.

But wouldn't it be better to name the date file ContextGetAspectReturnTypes.php and the class ContextGetAspectReturnTypes?
 
What do you prefer here?

**Comment by sascha-egerer** [comment]
> But wouldn't it be better to name the date file ContextGetAspectReturnTypes.php and the class ContextGetAspectReturnTypes and remove the ignore?

That would not work in all cases as some test files contain multiple class definitions. These files are more a set of components required for the test and not a plain class file.

**Comment by tlueder** [comment]
Any idea on why the php 7.3 and 7.4 test are failing?

**Comment by sascha-egerer** [comment]
@tlueder native type `mixed` does not exist in PHP < 8

**Pull request merged**
