### PR TITLE
Add support for extension installer

### PR DESCRIPTION
**Pull request by Baachi**
This pull request, adds support for phpstan extension installer.

### CODE REVIEW

**Comment by Baachi** [comment]
@sascha-egerer Thanks! Would you like to create a new tag? 
Asking for a friend :smile:

**Comment by sascha-egerer** [comment]
@Baachi done. Thank you for contributing

**Comment by ondrejmirtes** [comment]
I'm not sure how this helps to be honest since extension-installer requires PHPStan `>=0.11.6` and this extension supports only `^0.10` :)

**Comment by sascha-egerer** [comment]
Good point @ondrejmirtes but i am not sure if you could use the extension for PHPStan 0.11 by ignoring the PHPStan requirement. 
I've not yet tested the extension with PHPStan 0.11 but there is already an issue for that #7

**Pull request merged**
