### PR TITLE
Added check before define

### LINKED ISSUE #65: Constant TYPO3_version already defined
In case one uses conditional PHPStan config like:

phpstan.neon

```NEON
includes:
    - vendor/saschaegerer/phpstan-typo3/extension.neon
    - PHPStan/conditional.config.php
```

PHPStan/conditional.config.php

```PHP
<?php

declare(strict_types=1);

use TYPO3\CMS\Core\Information\Typo3Version;

$config = [];

$typo3Version = new Typo3Version();
if (version_compare($typo3Version->getVersion(), '11.5.0', '<')) {
  $config['parameters']['ignoreErrors'][] = [
    'message' => '#Call to an undefined method TYPO3\\\\CMS\\\\Core\\\\Database\\\\Query\\\\QueryBuilder::executeQuery\(\).#',
    'path' => '../Classes/ViewHelpers/path.php',
    'count' => 1,
  ];
}

return $config;
```

PHP Notice is shown:

PHP Notice:  Constant TYPO3_version already defined in vendor/saschaegerer/phpstan-typo3/phpstan.bootstrap.php on line 20

### PR DESCRIPTION
**Pull request by tlueder**
Fixes #65

### CODE REVIEW

**Comment by sabbelasichon** [comment]
A little nitpicking, but could you write it a little bit more concise like that: https://github.com/sabbelasichon/typo3-rector/blob/main/typo3.constants.php#L5

**Comment by tlueder** [comment]
Absolutely, looks better this way.

**Comment by sabbelasichon** [comment]
@sascha-egerer Looks good to me

**Review by sabbelasichon — APPROVED** [review]

**Comment by sascha-egerer** [comment]
Looks ok but should not be required. I would like to discuss the reason for this change in the Issue first.

**Comment by sabbelasichon** [comment]
@sascha-egerer I am closing this Pull Request. Feel free to open it again.

**Pull request closed without merging**
