### PR TITLE
[TASK] Use TYPO3 12.4 for TYPO3 12

### PR DESCRIPTION
**Pull request by oliverklee**
TYPO3 12.4 AKA 12LTS has been released.

### CODE REVIEW

**Comment by oliverklee** [comment]
@sascha-egerer I think I need some help with getting the build green with this, please.

**Comment by oliverklee** [comment]
Rebased and repushed.

**Review by sascha-egerer — APPROVED** [review]

**Comment by sascha-egerer** [comment]
Oh man, i totally messed up the commits. Sorry, was a bit in hurry. So the real change is already merged. ;-)

**Comment by sascha-egerer** [comment]
Oh man, i totally messed up the commits. Sorry, was a bit in hurry. So the real change is already merged. ;-)

**Pull request merged**
