### PR TITLE
Update dependencies and make php-parse a dev dependency

### LINKED ISSUE #159: Add Support for TYPO3 v13.1
Hey, it would be cool if support for TYPO3 v13.1 could be added. V13.1 got released on 2024-04-23 (https://get.typo3.org/).
Right now it is not possible to install, due to version constraints on nikic/php-parser component:

```
  Problem 1
    - Root composer.json requires saschaegerer/phpstan-typo3 ^1.10 -> satisfiable by saschaegerer/phpstan-typo3[1.10.0].
    - typo3/cms-install 13.2.x-dev is an alias of typo3/cms-install dev-main and thus requires it to be installed too.
    - typo3/cms-install[dev-main, v13.1.0] require nikic/php-parser ^5.0.1 -> satisfiable by nikic/php-parser[v5.0.1, v5.0.2, 5.0.x-dev].
    - Conclusion: don't install nikic/php-parser v5.0.2 (conflict analysis result)
    - Root composer.json requires typo3/cms-install ^13.1 -> satisfiable by typo3/cms-install[v13.1.0, 13.2.x-dev (alias of dev-main)].
```

The support would allow extension developers to update their extensions, and early adopters to update their projects, while keeping phpstan working.

### PR DESCRIPTION
**Pull request by sascha-egerer**
Closes #159

### CODE REVIEW

**Comment by oliverklee** [comment]
From my experience, it can avoid a lot of hassle to run PHP-CS-Fixer and PHPStan only with one PHP version, one TYPO3 version and one set of dependencies (highest vs. lowest) on CI as the results otherwise tend to vary somewhat.

**Comment by sascha-egerer** [comment]
> From my experience, it can avoid a lot of hassle to run PHP-CS-Fixer and PHPStan only with one PHP version, one TYPO3 version and one set of dependencies (highest vs. lowest) on CI as the results otherwise tend to vary somewhat.

Actually I'm not a big fan of this but yes, it can become pretty complex. PHPStan itself does also have a special solution to support PHP 7.4. But i think... Time has come and PHP 7.4 support is ready to be dropped. I've now increased PHP requirement to 8.1 which should be fine for nearly everyone.

**Comment by oliverklee** [comment]
> I've now increased PHP requirement to 8.1 which should be fine for nearly everyone.

I'm using this package in quite a few extensions that still support TYPO3 11LTS (and all PHP versions that TYPO3 11LTS supports, i.e., also PHP 7.4.). I'd like to be able to use the latest features and bugfixes and would appreciate either 7.4 support as long as TYPO3 11LTS is officially supported, or one last 7.4-compatible release before this PR gets merged. Thanks! :pray:

**Comment by sascha-egerer** [comment]
@oliverklee Here you go. I've now just adjusted some PHPCS rules so PHPCS is also happy when using PHP 7.4

**Comment by oliverklee** [comment]
@sascha-egerer Oh, thanks! :heart:

**Pull request merged**
